#!/usr/bin/env bash

s="$USER"

len=${#s}

for ((i = 0; i < len; i++)); do
	c="${s:i:1}"
	echo "i:$i th character is $c"
done


# gives us a shell safe way that can be parsed
echo "${s@A}"
echo "${s@a}" # what is this ?

echo "${s@Q}" # this is to quote it
echo "${s@U}" # this is to uppercase it


