#!/usr/bin/env bash

filename='my-file'

echo "$filename."{txt,jpg,mov}

echo
arr=( "$filename."{txt,jpg,mov} )
for item  in "${arr[@]}"
do
	echo "$item "
done

echo

arr=(/etc/{foo,bar}/{1,2,3})
for item  in "${arr[@]}"
do
	echo "$item "
done
