#!/usr/bin/env bash

declare -A shells
# while IFS=: read -ra array; do # we can store it into an array ?
while IFS=: read -r name pass uid gid gecos home shell; do
	# skip comments
	if [[ $name == '#'* ]]; then
		continue
	fi
	
	shells[$name]=$shell
done < /etc/passwd

echo "$USER has the shell : ${shells[$USER]}"
declare -p shells
