#!/usr/bin/env bash

greet() ( # note we have used parenthesis
	name=$1
	echo "hello $name"
)

goodbye() {
	name=$1
	echo "goodbye $name"
}

# something like if __name__ == '__main__'

if ! (return 2>/dev/null); then # we are able to return if and only if we are being sourced
	echo "from library"
	greet dave
	goodbye john
fi
