#!/usr/bin/env bash

greet() {
	echo "hello $1"
}

goodbye() {
	echo "goodbye $1"
}

# something like if __name__ == '__main__'

if ! (return 2>/dev/null); then # we are able to return if and only if we are being sourced
	echo "from library"
	greet dave
	goodbye john
fi
