#!/usr/bin/env bash

# mapfile and readarray both are same

array=()
# read file into array
while read -r line ; do
	array+=("$line")
done < ./data.txt

printf '<%s>\n' "${array[@]}"

echo
# the name the variable is array and it is optional ?
# mapfile doesn't trim the delimiter by default
mapfile array < data.txt
printf '<%s>\n' "${array[@]}"


echo
mapfile -t array < data.txt # we are reading the whole file into the array
# so be sure that the file is not too big

printf '<%s>\n' "${array[@]}"

echo
mapfile -t -n 2 foo < data.txt # -n 2 limits it
printf '<%s>\n' "${foo[@]}"

echo
# map file with a callback
my-func() {
	local line=$1
	echo "(mapfile) called with line: $line"
}
mapfile -t -C my-func -c 1 foo < ./data.txt # -c 1, read one at a time and fire the callback
printf '<%s>\n' "${foo[@]}"
