#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
	echo "Error: file name(s) not supplied. " >&2
	echo "Usage: $0 <file_name> [ <file_name> ]"
fi

create_bash_executable() {
	local file_name=$1
	if [[ -f $file_name ]]; then
		echo "File: $file_name already exists; Not overwriting" >&2
		exit 1
	fi

	touch "$file_name"
	echo "#!/usr/bin/env bash" > "$file_name"
	chmod +x "$file_name"
}

for file_name in "$@"; do
	create_bash_executable "$file_name"
done

