#!/usr/bin/env bash

echo hi
echo $? # 0 if success

echo

echo hi | grep bye
# echo $? # echo worked but grep failed, $? always shows the status of the last command
# how to check the status of each of the command

cat /this-doesnt-exist | tr , :

# we can have `set -o pipefail`, but not recommended
echo
cat /this-doesnt-exist | tr , :
echo "${PIPESTATUS[*]}"

echo
(exit)

( exit 4 ) | ( exit 7 ) | ( exit 100 ) | (exit 0)
echo "${PIPESTATUS[*]}"
